export const MEETINGS = [
  {
    id: '1',
    title: '한강 저녁 러닝',
    date: '2026-07-31',
    time: '19:30',
    location: '여의도 한강공원 물빛광장',
    district: '영등포',
    pace: '5~6분/km',
    capacity: 12,
    joined: 7,
    leader: '김달리',
    memo: '초보자 환영! 5km 코스 예정',
  },
  {
    id: '2',
    title: '서울숲 새벽 크루런',
    date: '2026-08-01',
    time: '06:00',
    location: '서울숲 2문 앞',
    district: '성동',
    pace: '4~5분/km',
    capacity: 8,
    joined: 8,
    leader: '이빨리',
    memo: '페이스 유지 필수',
  },
  {
    id: '3',
    title: '올림픽공원 주말런',
    date: '2026-08-02',
    time: '08:00',
    location: '올림픽공원 평화의 문',
    district: '송파',
    pace: '6~7분/km',
    capacity: 15,
    joined: 5,
    leader: '박천천',
    memo: '10km 코스, 천천히 완주',
  },
  {
    id: '4',
    title: '북한산 트레일런',
    date: '2026-08-03',
    time: '07:30',
    location: '북한산 우이역 입구',
    district: '강북',
    pace: '7분+/km',
    capacity: 10,
    joined: 3,
    leader: '최산악',
    memo: '산악화 권장',
  },
];

export const DISTRICTS = ['전체', '영등포', '성동', '송파', '강북', '강남', '마포'];
export const PACES = ['전체', '4~5분/km', '5~6분/km', '6~7분/km', '7분+/km'];

export const MEMBERS = [
  { id: 'm1', name: '김달리', avatar: 'A', attended: true },
  { id: 'm2', name: '이속도', avatar: 'B', attended: true },
  { id: 'm3', name: '박훈련', avatar: 'C', attended: false },
  { id: 'm4', name: '최마라', avatar: 'D', attended: true },
  { id: 'm5', name: '정스피드', avatar: 'E', attended: false },
  { id: 'm6', name: '강러너', avatar: 'F', attended: true },
  { id: 'm7', name: '윤달림', avatar: 'G', attended: null },
];

export const RUNNING_RECORDS = [
  { date: '2026-07-28', distance: 5.2, duration: 28, memo: '한강 나이트런' },
  { date: '2026-07-25', distance: 10.0, duration: 58, memo: '서울숲 롱런' },
  { date: '2026-07-22', distance: 3.5, duration: 21, memo: '가볍게 동네런' },
  { date: '2026-07-18', distance: 7.8, duration: 45, memo: '올림픽공원' },
];

export const NOTICES = [
  {
    id: 'n1',
    author: '김달리',
    role: '리더',
    avatar: 'A',
    time: '2시간 전',
    content: '이번 주 토요일 모임 장소가 변경됩니다! 여의도 물빛광장 -> 반포 한강공원 잔디마당으로 변경됩니다. 꼭 확인해주세요.',
    likes: 12,
    comments: 3,
    liked: false,
  },
  {
    id: 'n2',
    author: '김달리',
    role: '리더',
    avatar: 'A',
    time: '1일 전',
    content: '7월 월간 러닝 결산! 이번 달 크루 총 누적 거리 423km 달성했습니다. 모두 수고하셨어요!',
    likes: 24,
    comments: 8,
    liked: true,
  },
  {
    id: 'n3',
    author: '이속도',
    role: '운영진',
    avatar: 'B',
    time: '3일 전',
    content: '8월 정기 모임 일정 공지드립니다. 매주 화, 목 저녁 7:30, 토요일 아침 8:00 고정 운영 예정입니다.',
    likes: 18,
    comments: 5,
    liked: false,
  },
];
